source 'https://rubygems.org'
  
  gem 'activerecord'
  gem 'standalone_migrations'
  gem 'pg'
  gem 'tty-box'
  gem 'annotate'
  gem 'rspec'
  gem 'shoulda'
  gem 'shoulda-matchers', '~> 3.0'
  gem 'database_cleaner'
